#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.11"
# dependencies = [
#   "PySide6",
#   "opencv-python",
#   "numpy",
#   "tifffile",
#   "imagecodecs",
# ]
# ///

import sys
import os

# Add the script's directory to sys.path so the package can be imported
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from puzzle_joiner.__main__ import main
main()
